apiVersion: v1
kind: Service
metadata:
  name: hello-devops
  namespace:  hello-devops
spec:
  selector:
    app: hello-devops
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
